queue_rules:
  - name: default
    conditions:
      # See https://docs.mergify.io/conditions/#validating-all-status-checks
      - 'check-success=9.10.1 on ubuntu-latest'
pull_request_rules:
  - name: 'Automatically merge pull requests'
    conditions:
      - 'label=merge me'
      - '#approved-reviews-by>=1'
      - '#changes-requested-reviews-by=0'
    actions:
      queue:
        name: default
        method: squash
  - name: 'Delete head branch after merge'
    conditions:
      - merged
    actions:
      delete_head_branch: {}
